class CLASS(Helmet_Phase1_Base) {
    model = QCLASS(Helmets_Phase1);
    camo = "Base";
};
class CLASS(Helmet_Phase1_CR): CLASS(Helmet_Phase1_Base) { camo = "CR"; };
class CLASS(Helmet_Phase1_CT): CLASS(Helmet_Phase1_Base) { camo = "CT"; };
class CLASS(Helmet_Phase1_CT_v2): CLASS(Helmet_Phase1_Base) { camo = "CT_v2"; };
class CLASS(Helmet_Phase1_CT_v3): CLASS(Helmet_Phase1_Base) { camo = "CT_v3"; };
class CLASS(Helmet_Phase1_CT_v4): CLASS(Helmet_Phase1_Base) { camo = "CT_v4"; };
class CLASS(Helmet_Phase1_SCT): CLASS(Helmet_Phase1_Base) { camo = "SCT"; };
class CLASS(Helmet_Phase1_VCT): CLASS(Helmet_Phase1_Base) { camo = "VCT"; };
class CLASS(Helmet_Phase1_CLC): CLASS(Helmet_Phase1_Base) { camo = "CLC"; };
class CLASS(Helmet_Phase1_CPL): CLASS(Helmet_Phase1_Base) { camo = "CPL"; };
class CLASS(Helmet_Phase1_CS): CLASS(Helmet_Phase1_Base) { camo = "CS"; };
class CLASS(Helmet_Phase1_CSS): CLASS(Helmet_Phase1_Base) { camo = "CSS"; };
class CLASS(Helmet_Phase1_CSFC): CLASS(Helmet_Phase1_Base) { camo = "CSFC"; };
class CLASS(Helmet_Phase1_CMS): CLASS(Helmet_Phase1_Base) { camo = "CMS"; };
class CLASS(Helmet_Phase1_CSM): CLASS(Helmet_Phase1_Base) { camo = "CSM"; };
class CLASS(Helmet_Phase1_Recruit_CamoBrown): CLASS(Helmet_Phase1_Base) { camo = "Recruit_CamoBrown"; };
class CLASS(Helmet_Phase1_Recruit_CamoGrey): CLASS(Helmet_Phase1_Base) { camo = "Recruit_CamoGrey"; };
class CLASS(Helmet_Phase1_Enlisted_CamoBrown): CLASS(Helmet_Phase1_Base) { camo = "Enlisted_CamoBrown"; };
class CLASS(Helmet_Phase1_Enlisted_CamoGrey): CLASS(Helmet_Phase1_Base) { camo = "Enlisted_CamoGrey"; };
class CLASS(Helmet_Phase1_NCO_CamoBrown): CLASS(Helmet_Phase1_Base) { camo = "NCO_CamoBrown"; };
class CLASS(Helmet_Phase1_NCO_CamoGrey): CLASS(Helmet_Phase1_Base) { camo = "NCO_CamoGrey"; };
class CLASS(Helmet_Phase1_Officer_CamoBrown): CLASS(Helmet_Phase1_Base) { camo = "Officer_CamoBrown"; };
class CLASS(Helmet_Phase1_Officer_CamoGrey): CLASS(Helmet_Phase1_Base) { camo = "Officer_CamoGrey"; };