class CLASS(Helmet_Phase1_Pilot_Base);
P1_PILOT_HELMET_VISOR_CUSTOM(Bailout,Kyber);
P1_PILOT_HELMET_VISOR_CUSTOM(Blue,Bacta);
//P1_PILOT_HELMET_CUSTOM(Evo);
P1_PILOT_HELMET_CUSTOM(Flip);
P1_PILOT_HELMET_CUSTOM(Gravestone);
P1_PILOT_HELMET_CUSTOM(Lacker);
P1_PILOT_HELMET_VISOR_CUSTOM(Mischief,Bacta);
