class CLASS(Helmet_Phase1_ARMR_Base);
P1_ARMR_HELMET_VISOR_CUSTOM(Dexus,Bacta);
//P1_ARMR_HELMET_VISOR_CUSTOM(Grey,Bacta);
P1_ARMR_HELMET_CUSTOM(Reaper);
P1_ARMR_HELMET_CUSTOM(Rippin);
P1_ARMR_HELMET_CUSTOM(Winter);
