HELMET_HOLDER(BNA_KC_HelmetHolder_ARC, [KC] SF ARC Helm, BNA_KC_Helmet_ARC, "SF")
HELMET_HOLDER(BNA_KC_HelmetHolder_ARF, [KC] SF ARF Helm, BNA_KC_Helmet_ARF, "SF")
HELMET_HOLDER(BNA_KC_HelmetHolder_BARC, [KC] SF BARC Helm, BNA_KC_Helmet_BARC, "SF")