HELMET_HOLDER(BNA_KC_HelmetHolder_ARC, [KC] SF ARC Helm, BNA_KC_Helmet_ARC, "SF")
HELMET_HOLDER(BNA_KC_HelmetHolder_ARC_v2, [KC] SF ARC Helm (v2), BNA_KC_Helmet_ARC_v2, "SF")
HELMET_HOLDER(BNA_KC_HelmetHolder_ARC_Night, [KC] SF ARC Helm (Night), BNA_KC_Helmet_ARC_Night, "SF")
HELMET_HOLDER(BNA_KC_HelmetHolder_ARF, [KC] SF ARF 01 Helm (Enlisted), BNA_KC_Helmet_ARF, "SF")
HELMET_HOLDER(BNA_KC_HelmetHolder_ARF_v2, [KC] SF ARF 01 Helm (Enlisted, v2), BNA_KC_Helmet_ARF_v2, "SF")
HELMET_HOLDER(BNA_KC_HelmetHolder_BARC, [KC] SF BARC Helm, BNA_KC_Helmet_BARC, "SF")