class CLASS(Helmet_Phase2_Axel)
{
    model = QCLASS(Helmets_Phase2_Custom);
    camo = "Axel";
};
class CLASS(Helmet_Phase2_Bob): CLASS(Helmet_Phase2_Axel) { camo = "Bob"; };
class CLASS(Helmet_Phase2_Burnt): CLASS(Helmet_Phase2_Axel) { camo = "Burnt"; };
class CLASS(Helmet_Phase2_Dexus): CLASS(Helmet_Phase2_Axel) { camo = "Dexus"; };
class CLASS(Helmet_Phase2_Evo): CLASS(Helmet_Phase2_Axel) { camo = "Evo"; };
class CLASS(Helmet_Phase2_Grey): CLASS(Helmet_Phase2_Axel) { camo = "Grey"; };
class CLASS(Helmet_Phase2_Harry): CLASS(Helmet_Phase2_Axel) { camo = "Harry"; };
class CLASS(Helmet_Phase2_Hazard): CLASS(Helmet_Phase2_Axel) { camo = "Hazard"; };
class CLASS(Helmet_Phase2_Jackal): CLASS(Helmet_Phase2_Axel) { camo = "Jackal"; };
class CLASS(Helmet_Phase2_Jaws): CLASS(Helmet_Phase2_Axel) { camo = "Jaws"; };
class CLASS(Helmet_Phase2_Jester): CLASS(Helmet_Phase2_Axel) { camo = "Jester"; };
class CLASS(Helmet_Phase2_Joe): CLASS(Helmet_Phase2_Axel) { camo = "Joe"; };
class CLASS(Helmet_Phase2_Keeli): CLASS(Helmet_Phase2_Axel) { camo = "Keeli"; };
class CLASS(Helmet_Phase2_Keeli_CamoBrown): CLASS(Helmet_Phase2_Axel) { camo = "Keeli_CamoBrown"; };
class CLASS(Helmet_Phase2_Keeli_CamoGrey): CLASS(Helmet_Phase2_Axel) { camo = "Keeli_CamoGrey"; };
class CLASS(Helmet_Phase2_Leon): CLASS(Helmet_Phase2_Axel) { camo = "Leon"; };
class CLASS(Helmet_Phase2_Lou): CLASS(Helmet_Phase2_Axel) { camo = "Lou"; };
class CLASS(Helmet_Phase2_Ox): CLASS(Helmet_Phase2_Axel) { camo = "Ox"; };
class CLASS(Helmet_Phase2_Patriot): CLASS(Helmet_Phase2_Axel) { camo = "Patriot"; };
class CLASS(Helmet_Phase2_Rodger): CLASS(Helmet_Phase2_Axel) { camo = "Rodger"; };
class CLASS(Helmet_Phase2_Sage): CLASS(Helmet_Phase2_Axel) { camo = "Sage"; };
class CLASS(Helmet_Phase2_Scvrpio): CLASS(Helmet_Phase2_Axel) { camo = "Scvrpio"; };
class CLASS(Helmet_Phase2_Sogi): CLASS(Helmet_Phase2_Axel) { camo = "Sogi"; };
class CLASS(Helmet_Phase2_Star): CLASS(Helmet_Phase2_Axel) { camo = "Star"; };
class CLASS(Helmet_Phase2_Swoop): CLASS(Helmet_Phase2_Axel) { camo = "Swoop"; };
class CLASS(Helmet_Phase2_Sytha): CLASS(Helmet_Phase2_Axel) { camo = "Sytha"; };
class CLASS(Helmet_Phase2_Tugz): CLASS(Helmet_Phase2_Axel) { camo = "Tugz"; };
class CLASS(Helmet_Phase2_Vortex): CLASS(Helmet_Phase2_Axel) { camo = "Vortex"; };
class CLASS(Helmet_Phase2_Woods): CLASS(Helmet_Phase2_Axel) { camo = "Woods"; };