class CfgAmmo {
    class 3AS_M_MK43_AT;
    class CLASS(MK43_AT): 3AS_M_MK43_AT {
        SCOPE_PUBLIC;
        aiAmmoUsageFlags = "128 + 256";
        airFriction = 0.085;
        airLock = 2;
        ace_rearm_caliber = 250;
        ace_vehicle_damage_incendiary = 1;
        cost = 500;
        CraterEffects = "ATMissileCrater";
        craterShape = "";
        craterWaterEffects = "ImpactEffectsWater";
        effectFly = "";
        effectsFire = "CannonFire";
        effectsMissile = "3AS_Rocket_effect_Blue_fly";
        effectsSmoke = "SmokeShellWhite";
        hit = 1400;
        indirectHit = 20;
        indirectHitRange = 2;
        irLock = 2;
        lockSeekRadius = 100;
        maxControlRange = 2000;
        maxSpeed = 180;
        missileKeepLockedCone = 160;
        missileLockCone = 4.5;
        missileLockMaxDistance = 2000;
        missileLockMaxSpeed = 35;
        missileLockMinDistance = 50;
        missileManualControlCone = 45;
        model = "\A3\weapons_f\launchers\rpg32\tbg32v_rocket.p3d";
        submunitionAmmo = "3AS_ammo_Penetrator_MK43";
        submunitionDirectionType = "SubmunitionModelDirection";
        submunitionInitSpeed = 1000;
        thrust = 45;
        thrustTime = 5;
        timeToLive = 22;
        trackLead = 0.9;
        trackOversteer = 1.5;
        typicalSpeed = 160;
        warheadName = "HE";
        weaponLockSystem = "2 + 16";
    };

    class 3AS_M_MK39_AA;
    class CLASS(MK39_AA): 3AS_M_MK39_AA {
        SCOPE_PUBLIC;
        ace_rearm_caliber = 250;
        ace_vehicle_damage_incendiary = 1;
        afMax = 200;
        aiAmmoUsageFlags = 256;
        airFriction = 0.145;
        airLock = 2;
        cost = 1000;
        CraterEffects = "AAMissileCrater";
        effectsMissile = "3AS_Rocket_effect_Blue_fly";
        explosionEffects = "AAMissileExplosion";
        fuseDistance = 50;
        hit = 250;
        indirectHit = 120;
        indirectHitRange = 12;
        initTime = 0.25;
        itLock = 2;
        maneuvrability = 22;
        maxSpeed = 850;
        missileKeepLockedCone = 75;
        missileLockCone = 30;
        missileLockMaxDistance = 4500;
        missileLockMaxSpeed = 500;
        missileLockMinDistance = 100;
        model = "\A3\Weapons_F_beta\Launchers\titan\titan_missile_atl_fly.p3d";
        thrust = 380;
        thrustTime = 10;
        timeToLive = 30;
        trackLead = 0.95;
        trackOversteer = 1;
        typicalSpeed = 900;
        warheadName = "HE";
        weaponLockSystem = "2 + 16";
    };

    class 3AS_M_MK44_HE;
    class CLASS(MK44_HE): 3AS_M_MK44_HE {
        aiAmmoUsageFlags = "64 + 128";
        airFriction = 0.085;
        airLock = 2;
        cost = 300;
        CraterEffects = "ATMissileCrater";
        effectsMissile = "3AS_missile_effect_PLX_fly";
        explosionEffects = "ATMissileExplosion";
        fuseDistance = 50;
        hit = 100;
        indirectHit = 25;
        indirectHitRange = 10;
        irLock = 2;
        lockType = 0;
        manualControl = 1;
        manualControlOffset = 100;
        missileKeepLockedCone = 160;
        missileLockCone = 4.5;
        missileLockMaxDistance = 2000;
        missileLockMaxSpeed = 35;
        missileLockMinDistance = 50;
        missileManualControlCone = 60;
        model = "\A3\Weapons_F_beta\Launchers\titan\titan_missile_ap_fly";
        thrust = 45;
        thrustTime = 5;
        timeToLive = 22;
        triggerOnImpact = 0;
        warheadName = "HE";
    };
};
