#define MENU_PAGE_HOME 0
#define RANKMENU_PAGE_UNIFORMS 1

#define LOADOUTMENU_PAGE_SQUAD 1
#define LOADOUTMENU_PAGE_ROLE 2
#define LOADOUTMENU_PAGE_WEAPONS 3


#define LOADOUTS_RANKS_ENLISTED "CR", "CT", "SCT", "VCT", "CLC", "CPL"
#define LOADOUTS_RANKS_NCO "CS", "CSS", "CSFC", "CMS", "CSM"
#define LOADOUTS_RANKS_OFFICER "WO", "WO2", "WO3", "LT", "1LT", "CAP", "MAJ", "COM"
#define LOADOUTS_RANKS_LIST [LOADOUTS_RANKS_ENLISTED, LOADOUTS_RANKS_NCO, LOADOUTS_RANKS_OFFICER]