#define MENU_PAGE_HOME 0
#define RANKMENU_PAGE_UNIFORMS 1

#define LOADOUTMENU_PAGE_WEAPONS 1
#define LOADOUTMENU_GETPAGE ace_player getVariable [QQGVAR(LoadoutMenu_Page), MENU_PAGE_HOME]
#define LOADOUTMENU_SETPAGE(var1) ace_player setVariable [QQGVAR(LoadoutMenu_Page), var1]


#define LOADOUTS_RANKS_ENLISTED "CR", "CT", "SCT", "VCT", "CLC", "CPL"
#define LOADOUTS_RANKS_NCO "CS", "CSS", "CSFC", "CMS", "CSM"
#define LOADOUTS_RANKS_OFFICER "WO", "WO2", "WO3", "LT", "1LT", "CAP", "MAJ", "COM"
#define LOADOUTS_RANKS_LIST [LOADOUTS_RANKS_ENLISTED, LOADOUTS_RANKS_NCO, LOADOUTS_RANKS_OFFICER]
#define LOADOUTS_WEAPONS_LIST ["DC15A", "DC15S", "DC15C"]
#define LOADOUTS_KITS_LIST ["Rifleman", "Squad Leader"]