#define IDD_FUELDISPLAY 8000
#define IDC_FUELDISPLAY_BACKGROUND 9000
#define IDC_FUELDISPLAY_FUEL 9001

#define FUELDISPLAY_W 0.025
#define FUELDISPLAY_H 0.3
#define FUELDISPLAY_X 0.95
#define FUELDISPLAY_Y 0.5

#define FUELDISPLAY_FUEL_W FUELDISPLAY_W * 0.5
#define FUELDISPLAY_FUEL_H FUELDISPLAY_H * 0.95

#define JETPACK_FUEL_DEFAULT 200
#define JETPACK_SPEED_DEFAULT 2
#define JETPACK_STRENGTH_DEFAULT 15

#define FUELCAN_NONE ["", 0]