#define TYPE_EMP 0
#define TYPE_BACTA 1

#define EMP_RADIUS_DROID_DEFAULT 10
#define EMP_RADIUS_DROIDEKA_DEFAULT 10
#define EMP_RADIUS_VEHICLE_DEFAULT 10

#define BACTA_DURATION_DEFAULT 20
// TODO: Move to medical addon (when made)
#define MEDICAL_HEAL_RADIUS_DEFAULT 20
#define MEDICAL_HEAL_RATE_DEFAULT 0.5
#define MEDICAL_HEAL_MAXPATIENTS_DEFAULT -1