rmdir /s /q %temp%\BNA_KC_Gear
rmdir /s /q %temp%\BNA_KC_Weapons
rmdir /s /q %temp%\BNA_KC_Vehicles
rmdir /s /q %temp%\BNA_KC_Props
rmdir /s /q %temp%\BNA_KC_Scripts
rmdir /s /q %temp%\BNA_KC_ZeusAudioModule
rmdir /s /q %temp%\BNA_KC_Rancorbuh
rmdir /s /q %temp%\ChatWheelRedux
rmdir /s /q %temp%\BNA_KC_Legacy
rmdir /s /q %temp%\BNA_KC_Memes