class CfgPatches
{
    class BNA_KC_Props_PlaceableHelmets
    {
        addonRootClass= "BNA_KC_Props";
        author = "SweMonkey and DartRuffian";
        requiredVersion = 0.1;
        requiredAddons[] =
        {
            "BNA_KC_Core",
            "BNA_KC_Gear_Infantry",
            "BNA_KC_Gear_Armored",
            "BNA_KC_Gear_Aviation",
            "BNA_KC_Gear_SpecialForces",
            "BNA_KC_Gear_Customs"
            // All KC Helmets required
        };
        units[] =
        {
            // Infantry
            // Phase 1
            "BNA_KC_HelmetHolder_P1_CR",
            "BNA_KC_HelmetHolder_P1_CT",
            "BNA_KC_HelmetHolder_P1_CT_v2",
            "BNA_KC_HelmetHolder_P1_CT_v3",
            "BNA_KC_HelmetHolder_P1_CT_v4",
            "BNA_KC_HelmetHolder_P1_SCT",
            "BNA_KC_HelmetHolder_P1_VCT",
            "BNA_KC_HelmetHolder_P1_CLC",
            "BNA_KC_HelmetHolder_P1_CPL",
            "BNA_KC_HelmetHolder_P1_CS",
            "BNA_KC_HelmetHolder_P1_CSS",
            "BNA_KC_HelmetHolder_P1_CSFC",
            "BNA_KC_HelmetHolder_P1_CMS",
            "BNA_KC_HelmetHolder_P1_CSM",
            // Phase 2
            "BNA_KC_HelmetHolder_P2_CR",
            "BNA_KC_HelmetHolder_P2_CR_Legacy",
            "BNA_KC_HelmetHolder_P2_CT",
            "BNA_KC_HelmetHolder_P2_CT_v2",
            "BNA_KC_HelmetHolder_P2_CT_Legacy",
            "BNA_KC_HelmetHolder_P2_SCT",
            "BNA_KC_HelmetHolder_P2_SCT_Legacy",
            "BNA_KC_HelmetHolder_P2_VCT",
            "BNA_KC_HelmetHolder_P2_VCT_Legacy",
            "BNA_KC_HelmetHolder_P2_CLC",
            "BNA_KC_HelmetHolder_P2_CLC_Legacy",
            "BNA_KC_HelmetHolder_P2_CPL",
            "BNA_KC_HelmetHolder_P2_CS",
            "BNA_KC_HelmetHolder_P2_CS_Legacy",
            "BNA_KC_HelmetHolder_P2_CSS",
            "BNA_KC_HelmetHolder_P2_CSFC",
            "BNA_KC_HelmetHolder_P2_CMS",
            "BNA_KC_HelmetHolder_P2_CMS_Legacy",
            "BNA_KC_HelmetHolder_P2_CSM",
            "BNA_KC_HelmetHolder_P2_Officer",
            "BNA_KC_HelmetHolder_P2_WO",
            "BNA_KC_HelmetHolder_P2_WO2",
            "BNA_KC_HelmetHolder_P2_WO3",
            "BNA_KC_HelmetHolder_P2_LT",
            "BNA_KC_HelmetHolder_P2_1LT",
            "BNA_KC_HelmetHolder_P2_CPT",
            "BNA_KC_HelmetHolder_P2_MAJ",
            "BNA_KC_HelmetHolder_P2_COM",
            // Misc.
            "BNA_KC_HelmetHolder_AB",
            "BNA_KC_HelmetHolder_AB_v2",
            "BNA_KC_HelmetHolder_Engineer",
            "BNA_KC_HelmetHolder_Engineer_CamoBrown",
            "BNA_KC_HelmetHolder_Engineer_CamoGrey",
            "BNA_KC_HelmetHolder_Insulated",

            // Armored
            "BNA_KC_HelmetHolder_P1_Tanker",
            "BNA_KC_HelmetHolder_P1_Tanker_v2",
            "BNA_KC_HelmetHolder_P2_Tanker",
            "BNA_KC_HelmetHolder_P2_Tanker_v2",

            // Aviation
            "BNA_KC_HelmetHolder_P1_Pilot",
            "BNA_KC_HelmetHolder_P2_Pilot",

            // Special Forces
            "BNA_KC_HelmetHolder_ARC",
            "BNA_KC_HelmetHolder_ARC_v2",
            "BNA_KC_HelmetHolder_ARC_Night",
            "BNA_KC_HelmetHolder_ARF",
            "BNA_KC_HelmetHolder_ARF_v2",
            "BNA_KC_HelmetHolder_BARC",

            // Customs
            // Phase 1
            "BNA_KC_HelmetHolder_P1_Axel",
            "BNA_KC_HelmetHolder_P1_Burnt",
            "BNA_KC_HelmetHolder_P1_Burnt_Bacta",
            "BNA_KC_HelmetHolder_P1_Catholic",
            "BNA_KC_HelmetHolder_P1_Catholic_Kyber",
            "BNA_KC_HelmetHolder_P1_Defter",
            "BNA_KC_HelmetHolder_P1_Defter_Bacta",
            "BNA_KC_HelmetHolder_P1_Dexus",
            "BNA_KC_HelmetHolder_P1_Dexus_Bacta",
            "BNA_KC_HelmetHolder_P1_Drake",
            "BNA_KC_HelmetHolder_P1_Drake_Bacta",
            "BNA_KC_HelmetHolder_P1_Fil",
            "BNA_KC_HelmetHolder_P1_Grey",
            "BNA_KC_HelmetHolder_P1_Hazard",
            "BNA_KC_HelmetHolder_P1_Howzer_Blue",
            "BNA_KC_HelmetHolder_P1_Howzer_Brown",
            "BNA_KC_HelmetHolder_P1_Jaws",
            "BNA_KC_HelmetHolder_P1_Jester",
            "BNA_KC_HelmetHolder_P1_Joe",
            "BNA_KC_HelmetHolder_P1_Joe_Crimson",
            "BNA_KC_HelmetHolder_P1_Keeli",
            "BNA_KC_HelmetHolder_P1_Keeli_Crimson",
            "BNA_KC_HelmetHolder_P1_Lou",
            "BNA_KC_HelmetHolder_P1_Lou_Plasma",
            "BNA_KC_HelmetHolder_P1_Ox",
            "BNA_KC_HelmetHolder_P1_Patriot",
            "BNA_KC_HelmetHolder_P1_Ponds",
            "BNA_KC_HelmetHolder_P1_Rev",
            "BNA_KC_HelmetHolder_P1_Rodger",
            "BNA_KC_HelmetHolder_P1_Sin",
            "BNA_KC_HelmetHolder_P1_Splashdown",
            "BNA_KC_HelmetHolder_P1_Swoop",
            "BNA_KC_HelmetHolder_P1_Woods",
            // Phase 2
            "BNA_KC_HelmetHolder_P2_Axel",
            "BNA_KC_HelmetHolder_P2_Bob",
            "BNA_KC_HelmetHolder_P2_Bob_Kyber",
            "BNA_KC_HelmetHolder_P2_Burnt",
            "BNA_KC_HelmetHolder_P2_Burnt_Bacta",
            "BNA_KC_HelmetHolder_P2_Dexus",
            "BNA_KC_HelmetHolder_P2_Dexus_Bacta",
            "BNA_KC_HelmetHolder_P2_Evo",
            "BNA_KC_HelmetHolder_P2_Fil",
            "BNA_KC_HelmetHolder_P2_FilSquad",
            "BNA_KC_HelmetHolder_P2_Grey",
            "BNA_KC_HelmetHolder_P2_Harry",
            "BNA_KC_HelmetHolder_P2_Hazard",
            "BNA_KC_HelmetHolder_P2_Jackal",
            "BNA_KC_HelmetHolder_P2_Jaws",
            "BNA_KC_HelmetHolder_P2_Jester",
            "BNA_KC_HelmetHolder_P2_Joe",
            "BNA_KC_HelmetHolder_P2_Joe_Crimson",
            "BNA_KC_HelmetHolder_P2_Keeli",
            "BNA_KC_HelmetHolder_P2_Keeli_Crimson",
            "BNA_KC_HelmetHolder_P2_Lou",
            "BNA_KC_HelmetHolder_P2_Lou_Plasma",
            "BNA_KC_HelmetHolder_P2_Leon",
            "BNA_KC_HelmetHolder_P2_Ox",
            "BNA_KC_HelmetHolder_P2_Patriot",
            "BNA_KC_HelmetHolder_P2_Ponds",
            "BNA_KC_HelmetHolder_P2_Rev",
            "BNA_KC_HelmetHolder_P2_Rodger",
            "BNA_KC_HelmetHolder_P2_Sage",
            "BNA_KC_HelmetHolder_P2_Scvrpio",
            "BNA_KC_HelmetHolder_P2_Sogi",
            "BNA_KC_HelmetHolder_P2_Splashdown",
            "BNA_KC_HelmetHolder_P2_Star",
            "BNA_KC_HelmetHolder_P2_Stone",
            "BNA_KC_HelmetHolder_P2_Swoop",
            "BNA_KC_HelmetHolder_P2_Sytha",
            "BNA_KC_HelmetHolder_P2_Tugz",
            "BNA_KC_HelmetHolder_P2_Tyrant",
            "BNA_KC_HelmetHolder_P2_Tyrant_Crimson",
            "BNA_KC_HelmetHolder_P2_Vortex",
            "BNA_KC_HelmetHolder_P2_Woods",
            // Snow
            "BNA_KC_HelmetHolder_Insulated_Dexus",
            "BNA_KC_HelmetHolder_Insulated_Joe",
            "BNA_KC_HelmetHolder_Insulated_Keeli",
            // Pilot P1
            "BNA_KC_HelmetHolder_P1_Pilot_Bailout",
            "BNA_KC_HelmetHolder_P1_Pilot_Blue",
            "BNA_KC_HelmetHolder_P1_Pilot_Blue_Bacta",
            "BNA_KC_HelmetHolder_P1_Pilot_Mischief",
            // Pilot P2
            "BNA_KC_HelmetHolder_P2_Pilot_Bailout",
            "BNA_KC_HelmetHolder_P2_Pilot_Blue",
            "BNA_KC_HelmetHolder_P2_Pilot_Blue_Bacta",
            "BNA_KC_HelmetHolder_P2_Pilot_Mischief",
            // Armored P1
            "BNA_KC_HelmetHolder_P1_Tanker_Grey",
            // Armored P2
            "BNA_KC_HelmetHolder_P2_Tanker_Catholic",
            "BNA_KC_HelmetHolder_P2_Tanker_Catholic_Kyber",
            "BNA_KC_HelmetHolder_P2_Tanker_Grey",
            // Special Forces
            "BNA_KC_HelmetHolder_ARC_Drake",
            "BNA_KC_HelmetHolder_ARC_Drake_Bacta",
            "BNA_KC_HelmetHolder_ARC_Hagrid",
            "BNA_KC_HelmetHolder_ARC_Hagrid_Plasma",
            "BNA_KC_HelmetHolder_ARC_Tyrant",
            "BNA_KC_HelmetHolder_ARC_Tyrant_Crimson",
            "BNA_KC_HelmetHolder_ARF_Patriot",
            "BNA_KC_HelmetHolder_ARF_Sin",
            "BNA_KC_HelmetHolder_ARF_Tugz",
            "BNA_KC_HelmetHolder_BARC_Rat",
            "BNA_KC_HelmetHolder_BARC_Rat_Crimson"
        };
        weapons[] = {};
    };
};