class CfgVehicles {
    class Sound;
    class CLASS(Sound_Base): Sound {
        SCOPE_PRIVATE;
        author = AUTHOR;
    };
    SOUND_OBJ(Restaurant,"[KC] Restaurant Ambience");
    SOUND_OBJ(Incoming,"[KC] Incoming Alarm");
    SOUND_OBJ(Disturbance,"[KC] Disturbance in the force");
    SOUND_OBJ(JediWarning,"[KC] Jedi Warning");
    SOUND_OBJ(ATTE_Alarm,"[KC] AT-TE Alarm");
    SOUND_OBJ(DK_Radio,"[KC] DK Radio Chatter");
    SOUND_OBJ(CarnageRoar,"[KC] Carnage Roar");
    SOUND_OBJ(CarnageRoar2,"[KC] Carnage Roar 2");
    SOUND_OBJ(CarnageRoar3,"[KC] Carnage Roar 3");
    SOUND_OBJ(CarnageRoar4,"[KC] Carnage Roar 4");
    SOUND_OBJ(COD_HammerDownCounterSign,"Hammer Down Countersign");
    SOUND_OBJ(COD_HammerDownProtocol,"Hammer Down Protocol");
    SOUND_OBJ(LetThereBeCarnage,"[KC] Let There Be Carnage");
    SOUND_OBJ(EPF_Radio,"[KC] Holownet News");
    SOUND_OBJ(EPF_Radio2,"[KC] Holownet News 2");
    SOUND_OBJ(EPF_Radio3,"[KC] Holownet News 3");
    SOUND_OBJ(EPF_PresidenteSpeech,"[KC] El Presidente Speech");
    SOUND_OBJ(TDI_Theme,"[KC] Total Drama Island Theme");
    SOUND_OBJ(PokeVillage,"[KC] Poke Village Theme");
    SOUND_OBJ(Droid_Marching,"[KC] CIS Droid March");
    SOUND_OBJ(Godzilla_Roar,"[KC] Godzilla Roar");
    SOUND_OBJ(Order_66,"[KC] Execute Order 66");
    SOUND_OBJ(Liberty,"[KC] RDF Anthem Radio");
    SOUND_OBJ(Liberty_Anthem,"[KC] RDF Anthem");
    SOUND_OBJ(Rural_Music,"[KC] El Workers");
};